#include "ObjExporter.h"
#include <fstream>
#include <iostream>

bool ObjExporter::Save(const ModelData& data, const std::string& outputPath) {
    std::ofstream outFile(outputPath);
    if (!outFile.is_open()) return false;

    // Standard OBJ file format headers
    outFile << "# Generated by SolidWorks C++ Granular Converter" << std::endl;

    int vertexIndex = 1; // OBJ is 1-based index

    // 1. Write Faces (Triangles)
    for (const auto& tri : data.triangles) {
        // v dot (.) is used for Objects (tri.v1.x)
        outFile << "v " << tri.v1.x << " " << tri.v1.y << " " << tri.v1.z << "\n";
        outFile << "v " << tri.v2.x << " " << tri.v2.y << " " << tri.v2.z << "\n";
        outFile << "v " << tri.v3.x << " " << tri.v3.y << " " << tri.v3.z << "\n";
        
        outFile << "f " << vertexIndex << " " << vertexIndex + 1 << " " << vertexIndex + 2 << "\n";
        vertexIndex += 3;
    }

    // 2. Write Edges (Continuous Chains)
    for (const auto& chain : data.edgeChains) {
        int startIdx = vertexIndex;
        for (const auto& pt : chain) {
            outFile << "v " << pt.x << " " << pt.y << " " << pt.z << "\n";
            vertexIndex++;
        }
        
        outFile << "l"; // Create an edge chain by connecting vertex indices
        for (int i = 0; i < chain.size(); ++i) {
            outFile << " " << (startIdx + i);
        }
        outFile << "\n";
    }

    outFile.close();                                                    // Close stream
    
    // std::endl is important to flush the RAM tank and ensure the user sees the output immediately
    std::cout << "ObjExporter: Successfully exported " << data.triangles.size() << " triangles and " 
              << data.edgeChains.size() << " edge chains to " << outputPath << std::endl;
    
    return true;
}
