#pragma once

// 1. Importing Windows COM support (Required for HRESULT, _bstr_t, etc.)
#include <windows.h>
#include <comdef.h>

// 2. Importing our Contract
#include "IConverterEngine.h"

// 2. Importing SolidWorks (The "Magic" Step)
// We remove 'raw_interfaces_only' to get high-level C++ wrappers that look like C#.
#import "C:\\Program Files\\SOLIDWORKS Corp\\SOLIDWORKS\\sldworks.tlb" no_namespace, named_guids
#import "C:\\Program Files\\SOLIDWORKS Corp\\SOLIDWORKS\\swconst.tlb" no_namespace, named_guids

// 3. The Implementation Class
// "public IConverterEngine" means we are implementing the contract we wrote earlier.
class SolidWorksEngine : public IConverterEngine {
public:
    // Constructor: Runs when we create the object
    SolidWorksEngine();
    
    // Destructor: We use 'default' because our smart pointers handle cleanup.
    virtual ~SolidWorksEngine() = default;

    // 4. Overriding the Contract
    // 'override' tells the compiler to check that this matches the interface exactly.
    // It is identical to 'override' in C#.
    bool OpenPart(const std::string& filePath) override;
    bool ConvertToObj(const std::string& outputPath) override;
    void ClosePart() override;

private:
    // 5. Member Variables (The "State")
    // These are COM Smart Pointers.
    // ISldWorksPtr is a class generated by the #import above.
    // It will automatically call Release() when this class is destroyed.
    ISldWorksPtr m_swApp;
    IModelDoc2Ptr m_swModel;
};
